plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/Users/korakot/Desktop/restaurant-epos"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/book-demo.html"
to = "/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/book-demo"
to = "/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/pay-setup/*"
to = "https://restaurant-epos-back-office-production.up.railway.app/api/siampay/onboard/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]